version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - gosec
    - misspell
    - noctx
    - prealloc
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (io.Closer).Close
    gosec:
      excludes:
        - G104
        - G304
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: _test\.go
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - go-egress-proxy
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
